from secrets import choice, randbelow

from tciph.key.symbols import symbols

min_length = 3
max_length = 6


def get_symbols():
    return "".join(choice(symbols) for _ in range(randbelow(max_length) + min_length))


def get_rotation():
    return randbelow(2)


characters = f"""
a="{get_symbols()}"
b="{get_symbols()}"
c="{get_symbols()}"
d="{get_symbols()}"
e="{get_symbols()}"
f="{get_symbols()}"
g="{get_symbols()}"
h="{get_symbols()}"
i="{get_symbols()}"
j="{get_symbols()}"
k="{get_symbols()}"
l="{get_symbols()}"
m="{get_symbols()}"
n="{get_symbols()}"
o="{get_symbols()}"
p="{get_symbols()}"
q="{get_symbols()}"
r="{get_symbols()}"
s="{get_symbols()}"
t="{get_symbols()}"
u="{get_symbols()}"
v="{get_symbols()}"
w="{get_symbols()}"
x="{get_symbols()}"
y="{get_symbols()}"
z="{get_symbols()}"

capital_a="{get_symbols()}"
capital_b="{get_symbols()}"
capital_c="{get_symbols()}"
capital_d="{get_symbols()}"
capital_e="{get_symbols()}"
capital_f="{get_symbols()}"
capital_g="{get_symbols()}"
capital_h="{get_symbols()}"
capital_i="{get_symbols()}"
capital_j="{get_symbols()}"
capital_k="{get_symbols()}"
capital_l="{get_symbols()}"
capital_m="{get_symbols()}"
capital_n="{get_symbols()}"
capital_o="{get_symbols()}"
capital_p="{get_symbols()}"
capital_q="{get_symbols()}"
capital_r="{get_symbols()}"
capital_s="{get_symbols()}"
capital_t="{get_symbols()}"
capital_u="{get_symbols()}"
capital_v="{get_symbols()}"
capital_w="{get_symbols()}"
capital_x="{get_symbols()}"
capital_y="{get_symbols()}"
capital_z="{get_symbols()}"

digit_0="{get_symbols()}"
digit_1="{get_symbols()}"
digit_2="{get_symbols()}"
digit_3="{get_symbols()}"
digit_4="{get_symbols()}"
digit_5="{get_symbols()}"
digit_6="{get_symbols()}"
digit_7="{get_symbols()}"
digit_8="{get_symbols()}"
digit_9="{get_symbols()}"

space="{get_symbols()}"
period="{get_symbols()}"
comma="{get_symbols()}"
apostrophe="{get_symbols()}"
question_mark="{get_symbols()}"
exclamation_mark="{get_symbols()}"
hyphen="{get_symbols()}"
equals="{get_symbols()}"
underscore="{get_symbols()}"

salt_0="{get_symbols()}"
salt_1="{get_symbols()}"
salt_2="{get_symbols()}"
salt_3="{get_symbols()}"
salt_4="{get_symbols()}"
salt_5="{get_symbols()}"
salt_6="{get_symbols()}"
salt_7="{get_symbols()}"
salt_8="{get_symbols()}"
salt_9="{get_symbols()}"
salt_10="{get_symbols()}"
salt_11="{get_symbols()}"
salt_12="{get_symbols()}"
salt_13="{get_symbols()}"
salt_14="{get_symbols()}"
salt_15="{get_symbols()}"
salt_16="{get_symbols()}"
salt_17="{get_symbols()}"
salt_18="{get_symbols()}"
salt_19="{get_symbols()}"
salt_20="{get_symbols()}"
salt_21="{get_symbols()}"
salt_22="{get_symbols()}"
salt_23="{get_symbols()}"
salt_24="{get_symbols()}"
salt_25="{get_symbols()}"

rotate={get_rotation()}
"""
