from secrets import choice, randbelow

from tciph.key.symbols import greek

min_length = 3
max_length = 5


def get_greek_symbols():
    return "".join(choice(greek) for _ in range(randbelow(max_length) + min_length))


def get_rotation():
    return randbelow(2)


characters = f"""
a="{get_greek_symbols()}"
b="{get_greek_symbols()}"
c="{get_greek_symbols()}"
d="{get_greek_symbols()}"
e="{get_greek_symbols()}"
f="{get_greek_symbols()}"
g="{get_greek_symbols()}"
h="{get_greek_symbols()}"
i="{get_greek_symbols()}"
j="{get_greek_symbols()}"
k="{get_greek_symbols()}"
l="{get_greek_symbols()}"
m="{get_greek_symbols()}"
n="{get_greek_symbols()}"
o="{get_greek_symbols()}"
p="{get_greek_symbols()}"
q="{get_greek_symbols()}"
r="{get_greek_symbols()}"
s="{get_greek_symbols()}"
t="{get_greek_symbols()}"
u="{get_greek_symbols()}"
v="{get_greek_symbols()}"
w="{get_greek_symbols()}"
x="{get_greek_symbols()}"
y="{get_greek_symbols()}"
z="{get_greek_symbols()}"

A = "{get_greek_symbols()}"
B = "{get_greek_symbols()}"
C = "{get_greek_symbols()}"
D = "{get_greek_symbols()}"
E = "{get_greek_symbols()}"
F = "{get_greek_symbols()}"
G = "{get_greek_symbols()}"
H = "{get_greek_symbols()}"
I = "{get_greek_symbols()}"
J = "{get_greek_symbols()}"
K = "{get_greek_symbols()}"
L = "{get_greek_symbols()}"
M = "{get_greek_symbols()}"
N = "{get_greek_symbols()}"
O = "{get_greek_symbols()}"
P = "{get_greek_symbols()}"
Q = "{get_greek_symbols()}"
R = "{get_greek_symbols()}"
S = "{get_greek_symbols()}"
T = "{get_greek_symbols()}"
U = "{get_greek_symbols()}"
V = "{get_greek_symbols()}"
W = "{get_greek_symbols()}"
X = "{get_greek_symbols()}"
Y = "{get_greek_symbols()}"
Z = "{get_greek_symbols()}"

digit_0="{get_greek_symbols()}"
digit_1="{get_greek_symbols()}"
digit_2="{get_greek_symbols()}"
digit_3="{get_greek_symbols()}"
digit_4="{get_greek_symbols()}"
digit_5="{get_greek_symbols()}"
digit_6="{get_greek_symbols()}"
digit_7="{get_greek_symbols()}"
digit_8="{get_greek_symbols()}"
digit_9="{get_greek_symbols()}"

space="{get_greek_symbols()}"
period="{get_greek_symbols()}"
comma="{get_greek_symbols()}"
apostrophe="{get_greek_symbols()}"
question_mark="{get_greek_symbols()}"
exclamation_mark="{get_greek_symbols()}"
hyphen="{get_greek_symbols()}"
equals="{get_greek_symbols()}"
underscore="{get_greek_symbols()}"
plus="{get_greek_symbols()}"
forward_slash="{get_greek_symbols()}"

salt_0="{get_greek_symbols()}"
salt_1="{get_greek_symbols()}"
salt_2="{get_greek_symbols()}"
salt_3="{get_greek_symbols()}"
salt_4="{get_greek_symbols()}"
salt_5="{get_greek_symbols()}"
salt_6="{get_greek_symbols()}"
salt_7="{get_greek_symbols()}"
salt_8="{get_greek_symbols()}"
salt_9="{get_greek_symbols()}"
salt_10="{get_greek_symbols()}"
salt_11="{get_greek_symbols()}"
salt_12="{get_greek_symbols()}"
salt_13="{get_greek_symbols()}"
salt_14="{get_greek_symbols()}"
salt_15="{get_greek_symbols()}"
salt_16="{get_greek_symbols()}"
salt_17="{get_greek_symbols()}"
salt_18="{get_greek_symbols()}"
salt_19="{get_greek_symbols()}"
salt_20="{get_greek_symbols()}"
salt_21="{get_greek_symbols()}"
salt_22="{get_greek_symbols()}"
salt_23="{get_greek_symbols()}"
salt_24="{get_greek_symbols()}"
salt_25="{get_greek_symbols()}"

rotate={get_rotation()}
""".strip(
    "\n"
)
